name: kjx_esports
description: KJX Esports Mobile App - Flutter client for the Node.js backend

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  # HTTP Client
  http: ^1.1.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # State Management
  provider: ^6.1.1
  
  # Navigation
  go_router: ^13.0.0
  
  # UI Components
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Date/Time
  intl: ^0.19.0
  
  # Forms
  flutter_form_builder: ^9.2.0
  form_builder_validators: ^11.0.0
  
  # Utils
  url_launcher: ^6.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
